In [1]:
import numpy as np


In [26]:
a = np.array(range(3))

In [27]:
a

array([0, 1, 2])

In [28]:
a[:-1] + a[1:]

array([1, 3])

In [29]:
a[::2]

array([0, 2])

In [30]:
a[1:][::2]

array([1])

In [44]:
def agg(a):
    return a[1:][::2] + a[::2]

In [46]:
%timeit agg(np.array(range(10000000)))

1 loops, best of 3: 779 ms per loop
