In [2]:
import numpy as np
import clodius.tiles as ct

ImportError: No module named fast

In [26]:
a = np.array(range(3))

In [27]:
a

array([0, 1, 2])

In [28]:
a[:-1] + a[1:]

array([1, 3])

In [29]:
a[::2]

array([0, 2])

In [30]:
a[1:][::2]

array([1])

In [44]:
def agg(a):
    return a[1:][::2] + a[::2]

In [46]:
%timeit agg(np.array(range(10000000)))

1 loops, best of 3: 779 ms per loop


In [7]:
import clodius.tiles as ct
import numpy as np

a = np.array(range(2**20))
print len(a)

1048576


In [8]:
%timeit ct.tile2(a, 8)

1000 loops, best of 3: 1.53 ms per loop


In [14]:
b = ct.tile2(a,8)

In [10]:
len(b)

131072

In [12]:
b[:10]

array([  28.,   92.,  156.,  220.,  284.,  348.,  412.,  476.,  540.,  604.])

In [13]:
0+1+2+3+4+5+6+7

28